# in case there is a docker issue where the port is already in use, run the following in terminal
# netstat -vanp tcp | grep 4466
# kill -9 <PID>

version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            database: prisma2
            user: yashar  
            password: 123456   
            migrations: true

